### ISSUE TITLE
Add `py.typed`

### ISSUE THREAD

**Issue by mfulgo** [jleclanche/python-iso18245#1]
It looks like most of the library already has types. It'd probably be a fairly small effort to run mypy against the package and create a release with a `py.typed` file included.

Thoughts?

**Comment by jleclanche** [comment]
Sure. Care to do a PR?

**Comment by mfulgo** [comment]
Closed by Release 1.2.0 (8601b3c7aebd23c74c8467197f1780f3eb95718a).
