### ISSUE TITLE
[Question] Release 1.2.0 ?

### ISSUE THREAD

**Issue by jakubczaplicki** [jleclanche/python-iso18245#3]
Dependabot detected release 1.2.0, but I am not seeing a tag for 1.2.0.
What changed ?

**Comment by jakubczaplicki** [comment]
doh! 1.2.0 is old too. But still.. no tags for 1.2.0 and no mention about it in this repo ?

**Comment by jleclanche** [comment]
I think it was just a mixup with tags on my part when i did the last release. For consistency I released 1.2.0 just now on git too.
