### ISSUE TITLE
Performance Optimizations

### ISSUE THREAD

**Issue by mfulgo** [jleclanche/python-iso18245#4]
The library could use a bit of a performance tweak during the call to `_load_csv`: While the CSV files are cached, the resource filename is not, which eats up much of the time the library spends finding an MCC.

<img width="1245" alt="image" src="https://github.com/jleclanche/python-iso18245/assets/1708893/9c5ec9ab-9178-4b0e-80cc-f824f751a4ab">

To get around this, the calculation of the full path should move inside the if statement checking the CSV cache.
```patch
 def _load_csv(path: str) -> List[List[str]]:
-	full_path = resource_filename("iso18245", os.path.join("data", path))
 	if path not in _cached_csv:
+		full_path = resource_filename("iso18245", os.path.join("data", path))
 		with open(full_path, "r") as f:
```

**Comment by jleclanche** [comment]
Thanks! Fix looks good to me, could you submit a PR to keep credit?
