### ISSUE TITLE
Task: Replace deprecated `pkg_resources`

### ISSUE THREAD

**Issue by mfulgo** [jleclanche/python-iso18245#9]
Just opening an issue in case someone else gets around to it before I have a chance:
```
.../python3.11/site-packages/iso18245/__init__.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import resource_filename
```

From that page:
> Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). ...

**Comment by Worldrider** [comment]
> Just opening an issue in case someone else gets around to it before I have a chance:
> 
> ```
> .../python3.11/site-packages/iso18245/__init__.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>     from pkg_resources import resource_filename
> ```
> 
> From that page:
> 
> > Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). ...

On python 3.12 it doesn't work anymore

```
Traceback (most recent call last):
  File "/***************.py", line 4, in <module>
    import iso18245
  File "/***************.venv/lib/python3.12/site-packages/iso18245/__init__.py", line 5, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by jleclanche** [comment]
Thanks! If you submit a PR I will merge it.
